# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 02:21
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagem',
            field=models.ImageField(null=True, upload_to=account.models.user_directory_path),
        ),
    ]
