# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 23:49
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/', upload_to=account.models.user_directory_path),
        ),
    ]
