# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 22:25
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagem',
            field=models.ImageField(default='img/user_avatar.png', null=True, upload_to=account.models.user_directory_path),
        ),
    ]
