# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 22:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import personagem.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('nivel', models.DecimalField(decimal_places=0, max_digits=5)),
                ('alcunha', models.CharField(max_length=60)),
                ('pontos', models.DecimalField(decimal_places=0, max_digits=19)),
                ('atributos', models.TextField()),
                ('vantagens', models.TextField()),
                ('desvantagens', models.TextField()),
                ('pericias', models.TextField()),
                ('peculiaridade', models.TextField(blank=True, null=True)),
                ('controle_animais', models.TextField(blank=True, null=True)),
                ('turkelva', models.TextField(blank=True, null=True)),
                ('magias', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(upload_to=personagem.models.user_directory_path)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
