# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0004_auto_20170420_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='jogador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
    ]
