# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import trocapeles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('imagem', models.ImageField(upload_to=trocapeles.models.user_directory_path_capa)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('imagem', models.ImageField(upload_to=trocapeles.models.user_directory_path_mapa)),
                ('ativo', models.BooleanField()),
            ],
        ),
    ]
